// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttachmentRequest struct {
	Pretext              string               `protobuf:"bytes,1,opt,name=pretext,proto3" json:"pretext,omitempty"`
	Fallback             string               `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	Color                string               `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	AuthorName           string               `protobuf:"bytes,4,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorLink           string               `protobuf:"bytes,5,opt,name=authorLink,proto3" json:"authorLink,omitempty"`
	AuthorIcon           string               `protobuf:"bytes,6,opt,name=authorIcon,proto3" json:"authorIcon,omitempty"`
	Title                string               `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	TitleLink            string               `protobuf:"bytes,8,opt,name=titleLink,proto3" json:"titleLink,omitempty"`
	Text                 string               `protobuf:"bytes,9,opt,name=text,proto3" json:"text,omitempty"`
	AttachmentType       string               `protobuf:"bytes,10,opt,name=attachmentType,proto3" json:"attachmentType,omitempty"`
	CallbackId           string               `protobuf:"bytes,11,opt,name=callbackId,proto3" json:"callbackId,omitempty"`
	ImageURL             string               `protobuf:"bytes,12,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	ThumbURL             string               `protobuf:"bytes,13,opt,name=thumbURL,proto3" json:"thumbURL,omitempty"`
	Footer               string               `protobuf:"bytes,14,opt,name=footer,proto3" json:"footer,omitempty"`
	FooterIcon           string               `protobuf:"bytes,15,opt,name=footerIcon,proto3" json:"footerIcon,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,16,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Fields               []*AttachmentField   `protobuf:"bytes,17,rep,name=fields,proto3" json:"fields,omitempty"`
	Actions              []*AttachmentAction  `protobuf:"bytes,18,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AttachmentRequest) Reset()         { *m = AttachmentRequest{} }
func (m *AttachmentRequest) String() string { return proto.CompactTextString(m) }
func (*AttachmentRequest) ProtoMessage()    {}
func (*AttachmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *AttachmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentRequest.Unmarshal(m, b)
}
func (m *AttachmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentRequest.Marshal(b, m, deterministic)
}
func (m *AttachmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentRequest.Merge(m, src)
}
func (m *AttachmentRequest) XXX_Size() int {
	return xxx_messageInfo_AttachmentRequest.Size(m)
}
func (m *AttachmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentRequest proto.InternalMessageInfo

func (m *AttachmentRequest) GetPretext() string {
	if m != nil {
		return m.Pretext
	}
	return ""
}

func (m *AttachmentRequest) GetFallback() string {
	if m != nil {
		return m.Fallback
	}
	return ""
}

func (m *AttachmentRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *AttachmentRequest) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *AttachmentRequest) GetAuthorLink() string {
	if m != nil {
		return m.AuthorLink
	}
	return ""
}

func (m *AttachmentRequest) GetAuthorIcon() string {
	if m != nil {
		return m.AuthorIcon
	}
	return ""
}

func (m *AttachmentRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AttachmentRequest) GetTitleLink() string {
	if m != nil {
		return m.TitleLink
	}
	return ""
}

func (m *AttachmentRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AttachmentRequest) GetAttachmentType() string {
	if m != nil {
		return m.AttachmentType
	}
	return ""
}

func (m *AttachmentRequest) GetCallbackId() string {
	if m != nil {
		return m.CallbackId
	}
	return ""
}

func (m *AttachmentRequest) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *AttachmentRequest) GetThumbURL() string {
	if m != nil {
		return m.ThumbURL
	}
	return ""
}

func (m *AttachmentRequest) GetFooter() string {
	if m != nil {
		return m.Footer
	}
	return ""
}

func (m *AttachmentRequest) GetFooterIcon() string {
	if m != nil {
		return m.FooterIcon
	}
	return ""
}

func (m *AttachmentRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *AttachmentRequest) GetFields() []*AttachmentField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *AttachmentRequest) GetActions() []*AttachmentAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

type AttachmentField struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Short                bool     `protobuf:"varint,3,opt,name=short,proto3" json:"short,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachmentField) Reset()         { *m = AttachmentField{} }
func (m *AttachmentField) String() string { return proto.CompactTextString(m) }
func (*AttachmentField) ProtoMessage()    {}
func (*AttachmentField) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *AttachmentField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentField.Unmarshal(m, b)
}
func (m *AttachmentField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentField.Marshal(b, m, deterministic)
}
func (m *AttachmentField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentField.Merge(m, src)
}
func (m *AttachmentField) XXX_Size() int {
	return xxx_messageInfo_AttachmentField.Size(m)
}
func (m *AttachmentField) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentField.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentField proto.InternalMessageInfo

func (m *AttachmentField) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AttachmentField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AttachmentField) GetShort() bool {
	if m != nil {
		return m.Short
	}
	return false
}

type AttachmentAction struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachmentAction) Reset()         { *m = AttachmentAction{} }
func (m *AttachmentAction) String() string { return proto.CompactTextString(m) }
func (*AttachmentAction) ProtoMessage()    {}
func (*AttachmentAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *AttachmentAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentAction.Unmarshal(m, b)
}
func (m *AttachmentAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentAction.Marshal(b, m, deterministic)
}
func (m *AttachmentAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentAction.Merge(m, src)
}
func (m *AttachmentAction) XXX_Size() int {
	return xxx_messageInfo_AttachmentAction.Size(m)
}
func (m *AttachmentAction) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentAction.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentAction proto.InternalMessageInfo

func (m *AttachmentAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttachmentAction) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AttachmentAction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AttachmentAction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AttachmentAction) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Response struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AttachmentRequest)(nil), "message.AttachmentRequest")
	proto.RegisterType((*AttachmentField)(nil), "message.AttachmentField")
	proto.RegisterType((*AttachmentAction)(nil), "message.AttachmentAction")
	proto.RegisterType((*Response)(nil), "message.Response")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x8b, 0xdb, 0x30,
	0x10, 0x6d, 0x36, 0xdf, 0x93, 0x26, 0x9b, 0x88, 0xa5, 0xa8, 0xa1, 0xb4, 0xc1, 0x87, 0x92, 0x93,
	0xb7, 0x64, 0x2f, 0x7b, 0x2a, 0xec, 0xa5, 0xb0, 0xb0, 0x2d, 0xc5, 0xd9, 0xfe, 0x00, 0xc5, 0x99,
	0x24, 0x66, 0x6d, 0xcb, 0xb5, 0xe4, 0xd0, 0xfe, 0xdb, 0xfe, 0x94, 0xa2, 0x91, 0x64, 0x9b, 0xb0,
	0xb7, 0x79, 0xef, 0x8d, 0xf5, 0xac, 0x79, 0x23, 0x98, 0x66, 0xa8, 0x94, 0x38, 0x62, 0x58, 0x94,
	0x52, 0x4b, 0x36, 0x74, 0x70, 0xf9, 0xe9, 0x28, 0xe5, 0x31, 0xc5, 0x5b, 0xa2, 0x77, 0xd5, 0xe1,
	0x56, 0x27, 0x19, 0x2a, 0x2d, 0xb2, 0xc2, 0x76, 0x06, 0xff, 0x7a, 0xb0, 0x78, 0xd0, 0x5a, 0xc4,
	0xa7, 0x0c, 0x73, 0x1d, 0xe1, 0xef, 0x0a, 0x95, 0x66, 0x1c, 0x86, 0x45, 0x89, 0x1a, 0xff, 0x68,
	0xde, 0x59, 0x75, 0xd6, 0xe3, 0xc8, 0x43, 0xb6, 0x84, 0xd1, 0x41, 0xa4, 0xe9, 0x4e, 0xc4, 0x2f,
	0xfc, 0x8a, 0xa4, 0x1a, 0xb3, 0x1b, 0xe8, 0xc7, 0x32, 0x95, 0x25, 0xef, 0x92, 0x60, 0x01, 0xfb,
	0x08, 0x20, 0x2a, 0x7d, 0x92, 0xe5, 0x0f, 0x91, 0x21, 0xef, 0x91, 0xd4, 0x62, 0x1a, 0xfd, 0x29,
	0xc9, 0x5f, 0x78, 0xbf, 0xad, 0x1b, 0xa6, 0xd1, 0x1f, 0x63, 0x99, 0xf3, 0x41, 0x5b, 0x37, 0x8c,
	0x71, 0xd5, 0x89, 0x4e, 0x91, 0x0f, 0xad, 0x2b, 0x01, 0xf6, 0x01, 0xc6, 0x54, 0xd0, 0xa1, 0x23,
	0x52, 0x1a, 0x82, 0x31, 0xe8, 0xd1, 0xe5, 0xc6, 0x24, 0x50, 0xcd, 0x3e, 0xc3, 0x4c, 0xd4, 0x83,
	0x78, 0xfe, 0x5b, 0x20, 0x07, 0x52, 0x2f, 0x58, 0xf3, 0x3f, 0xb1, 0xbb, 0xf1, 0xe3, 0x9e, 0x4f,
	0xec, 0xff, 0x34, 0x8c, 0x99, 0x50, 0x92, 0x89, 0x23, 0xfe, 0x8a, 0x9e, 0xf8, 0x5b, 0x3b, 0x21,
	0x8f, 0x8d, 0xa6, 0x4f, 0x55, 0xb6, 0x33, 0xda, 0xd4, 0x6a, 0x1e, 0xb3, 0x77, 0x30, 0x38, 0x48,
	0xa9, 0xb1, 0xe4, 0x33, 0x52, 0x1c, 0x32, 0x7e, 0xb6, 0xa2, 0xfb, 0x5f, 0x5b, 0xbf, 0x86, 0x61,
	0xf7, 0x30, 0x7e, 0xf6, 0xa1, 0xf2, 0xf9, 0xaa, 0xb3, 0x9e, 0x6c, 0x96, 0xa1, 0x8d, 0x3d, 0xf4,
	0xb1, 0x87, 0x75, 0x47, 0xd4, 0x34, 0xb3, 0x2f, 0x30, 0x38, 0x24, 0x98, 0xee, 0x15, 0x5f, 0xac,
	0xba, 0xeb, 0xc9, 0x86, 0x87, 0x7e, 0x8b, 0x9a, 0x8d, 0xf8, 0x66, 0x1a, 0x22, 0xd7, 0xc7, 0xee,
	0x60, 0x28, 0x62, 0x9d, 0xc8, 0x5c, 0x71, 0x46, 0x9f, 0xbc, 0x7f, 0xe5, 0x93, 0x07, 0xea, 0x88,
	0x7c, 0x67, 0xb0, 0x85, 0xeb, 0x8b, 0xf3, 0x9a, 0xcc, 0x3a, 0xed, 0xcc, 0x6e, 0xa0, 0x7f, 0x16,
	0x69, 0x85, 0x6e, 0xb1, 0x2c, 0x30, 0xac, 0x3a, 0xc9, 0x52, 0xd3, 0x56, 0x8d, 0x22, 0x0b, 0x82,
	0x33, 0xcc, 0x2f, 0x1d, 0x4d, 0xaa, 0xb9, 0xd9, 0x31, 0x7b, 0x28, 0xd5, 0x75, 0xd2, 0x57, 0xad,
	0xa4, 0x0d, 0x67, 0xf2, 0xed, 0x3a, 0xce, 0xa4, 0x5a, 0x7b, 0xf7, 0xda, 0xde, 0x73, 0xe8, 0x56,
	0x65, 0xea, 0x96, 0xd2, 0x94, 0xc1, 0x3d, 0x8c, 0x22, 0x54, 0x85, 0xcc, 0x15, 0x9d, 0x1d, 0xcb,
	0xbd, 0xf5, 0x9b, 0x46, 0x54, 0x9b, 0x97, 0xe3, 0x26, 0xe2, 0x2c, 0x3d, 0xdc, 0xfc, 0x84, 0xd9,
	0x77, 0x5b, 0x6e, 0xb1, 0x3c, 0x27, 0x31, 0xb2, 0xaf, 0x30, 0xd9, 0x62, 0xbe, 0x77, 0x2c, 0x5b,
	0xbe, 0x32, 0x4b, 0xf7, 0x20, 0x97, 0x8b, 0x5a, 0xf3, 0xee, 0xc1, 0x9b, 0xdd, 0x80, 0xe2, 0xbd,
	0xfb, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x26, 0x98, 0x09, 0xfd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	SendMessage(ctx context.Context, in *AttachmentRequest, opts ...grpc.CallOption) (*Response, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendMessage(ctx context.Context, in *AttachmentRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/message.MessageService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	SendMessage(context.Context, *AttachmentRequest) (*Response, error)
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) SendMessage(ctx context.Context, req *AttachmentRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendMessage(ctx, req.(*AttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
